# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DepolarizerMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DepolarizerMessage.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x44\x65polarizerMessage.proto\"\xd7\x06\n\x12\x44\x65polarizerMessage\x12\n\n\x02id\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\x03\x12\x12\n\nrespond_id\x18\x03 \x01(\r\x12\x19\n\x11respond_timestamp\x18\x04 \x01(\x03\x12,\n\x07\x63ommand\x18\x05 \x02(\x0e\x32\x1b.DepolarizerMessage.Command\x12/\n\tdata_type\x18\x06 \x01(\x0e\x32\x1c.DepolarizerMessage.DataType\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x01\x12\r\n\x05state\x18\x08 \x01(\r\x12\x0f\n\x07\x63omment\x18\t \x01(\t\x12.\n\x04\x66map\x18\n \x01(\x0b\x32 .DepolarizerMessage.FrequencyMap\x12\x11\n\x06status\x18\x0b \x01(\r:\x01\x30\x1aV\n\tFrequency\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x11\n\tfrequency\x18\x02 \x02(\x01\x12\x0e\n\x06\x65nergy\x18\x03 \x01(\x01\x12\x13\n\x0b\x61ttenuation\x18\x04 \x01(\x01\x1a@\n\x0c\x46requencyMap\x12\x30\n\tfrequency\x18\x01 \x03(\x0b\x32\x1d.DepolarizerMessage.Frequency\"n\n\x07\x43ommand\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03SET\x10\x01\x12\t\n\x05START\x10\x02\x12\x08\n\x04STOP\x10\x03\x12\t\n\x05PAUSE\x10\x04\x12\x0c\n\x08\x43ONTINUE\x10\x05\x12\x08\n\x04INFO\x10\x06\x12\x0b\n\x07TURN_ON\x10\x07\x12\x0c\n\x08TURN_OFF\x10\x08\"\xdf\x01\n\x08\x44\x61taType\x12\x0b\n\x07\x43URRENT\x10\x00\x12\x0b\n\x07INITIAL\x10\x01\x12\t\n\x05\x46INAL\x10\x02\x12\t\n\x05SPEED\x10\x03\x12\x08\n\x04STEP\x10\x04\x12\x0f\n\x0b\x41TTENUATION\x10\x05\x12\x13\n\x0fHARMONIC_NUMBER\x10\x06\x12\n\n\x06STATUS\x10\x07\x12\x18\n\x14REVOLUTION_FREQUENCY\x10\x08\x12\t\n\x05STATE\x10\t\x12\t\n\x05WIDTH\x10\n\x12\r\n\tFREQUENCY\x10\x0b\x12\x08\n\x04\x46MAP\x10\x0c\x12\r\n\tGENERATOR\x10\r\x12\x0f\n\x0b\x44\x45POLARIZER\x10\x0e\"7\n\x05\x45rror\x12\x06\n\x02OK\x10\x00\x12\x13\n\x0fUNKNOWN_COMMAND\x10\x01\x12\x11\n\rBAD_GENERATOR\x10\x02'
)



_DEPOLARIZERMESSAGE_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='DepolarizerMessage.Command',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTINUE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TURN_ON', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TURN_OFF', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=491,
  serialized_end=601,
)
_sym_db.RegisterEnumDescriptor(_DEPOLARIZERMESSAGE_COMMAND)

_DEPOLARIZERMESSAGE_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='DepolarizerMessage.DataType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CURRENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INITIAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FINAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SPEED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STEP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ATTENUATION', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HARMONIC_NUMBER', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVOLUTION_FREQUENCY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATE', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WIDTH', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FREQUENCY', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FMAP', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GENERATOR', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEPOLARIZER', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=604,
  serialized_end=827,
)
_sym_db.RegisterEnumDescriptor(_DEPOLARIZERMESSAGE_DATATYPE)

_DEPOLARIZERMESSAGE_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='DepolarizerMessage.Error',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_COMMAND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_GENERATOR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=829,
  serialized_end=884,
)
_sym_db.RegisterEnumDescriptor(_DEPOLARIZERMESSAGE_ERROR)


_DEPOLARIZERMESSAGE_FREQUENCY = _descriptor.Descriptor(
  name='Frequency',
  full_name='DepolarizerMessage.Frequency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DepolarizerMessage.Frequency.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='DepolarizerMessage.Frequency.frequency', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='energy', full_name='DepolarizerMessage.Frequency.energy', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attenuation', full_name='DepolarizerMessage.Frequency.attenuation', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=423,
)

_DEPOLARIZERMESSAGE_FREQUENCYMAP = _descriptor.Descriptor(
  name='FrequencyMap',
  full_name='DepolarizerMessage.FrequencyMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='DepolarizerMessage.FrequencyMap.frequency', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=489,
)

_DEPOLARIZERMESSAGE = _descriptor.Descriptor(
  name='DepolarizerMessage',
  full_name='DepolarizerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DepolarizerMessage.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DepolarizerMessage.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='respond_id', full_name='DepolarizerMessage.respond_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='respond_timestamp', full_name='DepolarizerMessage.respond_timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='DepolarizerMessage.command', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='DepolarizerMessage.data_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='DepolarizerMessage.data', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='DepolarizerMessage.state', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='DepolarizerMessage.comment', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmap', full_name='DepolarizerMessage.fmap', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='DepolarizerMessage.status', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEPOLARIZERMESSAGE_FREQUENCY, _DEPOLARIZERMESSAGE_FREQUENCYMAP, ],
  enum_types=[
    _DEPOLARIZERMESSAGE_COMMAND,
    _DEPOLARIZERMESSAGE_DATATYPE,
    _DEPOLARIZERMESSAGE_ERROR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=884,
)

_DEPOLARIZERMESSAGE_FREQUENCY.containing_type = _DEPOLARIZERMESSAGE
_DEPOLARIZERMESSAGE_FREQUENCYMAP.fields_by_name['frequency'].message_type = _DEPOLARIZERMESSAGE_FREQUENCY
_DEPOLARIZERMESSAGE_FREQUENCYMAP.containing_type = _DEPOLARIZERMESSAGE
_DEPOLARIZERMESSAGE.fields_by_name['command'].enum_type = _DEPOLARIZERMESSAGE_COMMAND
_DEPOLARIZERMESSAGE.fields_by_name['data_type'].enum_type = _DEPOLARIZERMESSAGE_DATATYPE
_DEPOLARIZERMESSAGE.fields_by_name['fmap'].message_type = _DEPOLARIZERMESSAGE_FREQUENCYMAP
_DEPOLARIZERMESSAGE_COMMAND.containing_type = _DEPOLARIZERMESSAGE
_DEPOLARIZERMESSAGE_DATATYPE.containing_type = _DEPOLARIZERMESSAGE
_DEPOLARIZERMESSAGE_ERROR.containing_type = _DEPOLARIZERMESSAGE
DESCRIPTOR.message_types_by_name['DepolarizerMessage'] = _DEPOLARIZERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DepolarizerMessage = _reflection.GeneratedProtocolMessageType('DepolarizerMessage', (_message.Message,), {

  'Frequency' : _reflection.GeneratedProtocolMessageType('Frequency', (_message.Message,), {
    'DESCRIPTOR' : _DEPOLARIZERMESSAGE_FREQUENCY,
    '__module__' : 'DepolarizerMessage_pb2'
    # @@protoc_insertion_point(class_scope:DepolarizerMessage.Frequency)
    })
  ,

  'FrequencyMap' : _reflection.GeneratedProtocolMessageType('FrequencyMap', (_message.Message,), {
    'DESCRIPTOR' : _DEPOLARIZERMESSAGE_FREQUENCYMAP,
    '__module__' : 'DepolarizerMessage_pb2'
    # @@protoc_insertion_point(class_scope:DepolarizerMessage.FrequencyMap)
    })
  ,
  'DESCRIPTOR' : _DEPOLARIZERMESSAGE,
  '__module__' : 'DepolarizerMessage_pb2'
  # @@protoc_insertion_point(class_scope:DepolarizerMessage)
  })
_sym_db.RegisterMessage(DepolarizerMessage)
_sym_db.RegisterMessage(DepolarizerMessage.Frequency)
_sym_db.RegisterMessage(DepolarizerMessage.FrequencyMap)


# @@protoc_insertion_point(module_scope)
