hist_fpath : '/storage/hist/' #Path to store mapped event histograms
#fitres_file : '/home/lsrp/Control/polarimeter_dev/tmp/pol_fitres.txt'
regex_line : '2022*'

#Choose fit region (use physical coordinates and take in mind that each bin at the central region has length of 2 mm)
xrange : [-32,32]
n_files : 15
need_blur : False
blur_type : general_blur
fixQ : False
double_gauss: True
scale_hits: False
continue: True

mask:
    #- [-0.5,-1]
    #- [ 0.5,-1]
    #- [-0.5,2]
    #- [0.5,2]
    
initial_values:  
    E       : 4730 #MeV
    L       : 28000 #mm
    P       : 0.5
    V       : 1.
    Q       : 0.2024
    beta    : -2.413
    alpha_d : 0.
    mx      : 0. #mm
    my      : 0. #mm
    sx      : 5. #mm
    sy      : 3. #mm
    alpha_x1 : 2.23
    alpha_x2 : 0.
    alpha_y1 : 2.23
    alpha_y2 : 0.
    nx1      : 1.23
    nx2      : 1.23
    ny1     : 1.0
    ny2     : 1.0
    phi     : 0.0
    p1      : 0.0
    p2      : 0.0
    p3      : 0.0
    NL      : 100
    NR      : 100
    
fix_par:
    E       : True
    L       : True
    P       : False
    V       : True
    Q       : False
    beta    : False
    alpha_d : True
    mx      : False
    my      : False
    sx      : False
    sy      : False
    alpha_x1 : False
    alpha_x2 : False
    alpha_y1 : False
    alpha_y2 : False
    nx1     : False
    nx2     : False
    ny1     : False
    ny2     : False
    phi     : False
    NL      : False
    NR      : False
    p1      : True
    p2      : True
    p3      : True
    
par_err:  
    E       : 0.
    L       : 0.
    P       : 0.5
    V       : 0.1
    Q       : 0.5
    beta    : 1.0
    alpha_d : 0.1
    mx      : 5.0
    my      : 5.0
    sx      : 5.0
    sy      : 1.0
    alpha_x1 : 1.0
    alpha_x2 : 1.0
    alpha_y1 : 1.0
    alpha_y2 : 1.0
    nx1     : 0.1
    nx2     : 0.1
    ny1     : 0.1
    ny2     : 0.1
    phi     : 1.0
    NL      : 100
    NR      : 100
    p1      : 0.0
    p2      : 0.0
    p3      : 0.0
    
par_lim:  
    E       : [0.0, 100000]
    L       : [0.0, 100000]
    P       : [-10, 10.0]
    V       : [-1.0, 1.0]
    Q       : [-1.0, 1.0]
    beta    : [-7.0, 7.0]
    alpha_d : [-1.0, 1.0]
    mx      : [-20.0, +20.0]
    my      : [-10.0, +10.0]
    sx      : [0.1, 10.0]
    sy      : [0.1, 10.0]
    alpha_x1 : [0.1, 10.]
    alpha_x2 : [-10., 10.]
    alpha_y1 : [0.1, 10.]
    alpha_y2 : [-10., 10.]
    nx1     : [-5., 5.]
    nx2     : [-5., 5.]
    ny1     : [-5., 5.]
    ny2     : [-5., 5.]
    phi     : [-3.15,+3.15]
    p1     : [0,7]
    p2     : [0,7]
    p3     : [-100.,+100.]
    NL      : [1, 100000]
    NR      : [1, 100000]

